# Generated by Django 3.1.2 on 2022-03-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ocean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(default='NA', max_length=200)),
                ('releasedate', models.CharField(default='NA', max_length=200)),
                ('species', models.CharField(default='NA', max_length=200)),
                ('kingdom', models.CharField(default='NA', max_length=200)),
                ('genus', models.CharField(default='NA', max_length=200)),
                ('family', models.CharField(default='NA', max_length=200)),
                ('moleculetype', models.CharField(default='NA', max_length=200)),
                ('length', models.CharField(default='NA', max_length=200)),
                ('nuccompleteness', models.CharField(default='NA', max_length=200)),
                ('geolocation', models.CharField(default='NA', max_length=200)),
                ('host', models.CharField(default='NA', max_length=200)),
                ('biosample', models.CharField(default='NA', max_length=200)),
                ('description', models.CharField(default='NA', max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Dlsnp',
        ),
    ]
