# Generated by Django 3.1.2 on 2022-03-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ocean', '0002_auto_20220301_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocean',
            name='description',
            field=models.CharField(default='NA', max_length=300),
        ),
    ]
